#!/usr/bin/env bash
set -euo pipefail

DEFAULT_PROJECTS_ROOT="${PROJECTS_ROOT:-/projects/${USER:-${LOGNAME:-mosun}}}"
CAMPAIGN_ROOT="${CAMPAIGN_ROOT:-${DEFAULT_PROJECTS_ROOT}/mosun_susilo_fig5_efast}"
JULIA_VERSION="${JULIA_VERSION:-1.12.5}"
JULIA_BIN="${CAMPAIGN_ROOT}/tools/julia-${JULIA_VERSION}/bin/julia"
REPO_DIR="${CAMPAIGN_ROOT}/repo"
JULIA_PROJECT="${REPO_DIR}/julia"
LOG_ROOT="${LOG_ROOT:-${CAMPAIGN_ROOT}/logs}"
OUT_DIR="${SUSILO_EFAST_HOSSEINI_VPOP_OUT_DIR:-${REPO_DIR}/generated/figures/vpop_pruning/susilo_efast_hosseini2020_fig5_vpop250_20260505}"
NICE_LEVEL="${NICE_LEVEL:-5}"

mkdir -p "${LOG_ROOT}" "${OUT_DIR}"

export JULIA_DEPOT_PATH="${CAMPAIGN_ROOT}/julia_depot"
export JULIA_NUM_THREADS="${JULIA_NUM_THREADS:-100}"
export OPENBLAS_NUM_THREADS=1
export OMP_NUM_THREADS=1
export JULIA_PKG_PRECOMPILE_AUTO=0

log_file="${LOG_ROOT}/susilo_efast_hosseini2020_fig5_vpop_resim_$(date +%Y%m%d_%H%M%S).log"
echo "Running eFAST-derived Hosseini Fig.5 VPop candidate resimulation: out=${OUT_DIR}, threads=${JULIA_NUM_THREADS}, log=${log_file}"

SUSILO_EFAST_HOSSEINI_VPOP_OUT_DIR="${OUT_DIR}" \
SUSILO_EFAST_HOSSEINI_VPOP_SHARD_SIZE="${SUSILO_EFAST_HOSSEINI_VPOP_SHARD_SIZE:-100}" \
SUSILO_EFAST_HOSSEINI_VPOP_SOLVER="${SUSILO_EFAST_HOSSEINI_VPOP_SOLVER:-rodas4p}" \
SUSILO_EFAST_HOSSEINI_VPOP_HORIZON_DAYS="${SUSILO_EFAST_HOSSEINI_VPOP_HORIZON_DAYS:-84}" \
SUSILO_EFAST_HOSSEINI_VPOP_PROFILE_HORIZON_DAYS="${SUSILO_EFAST_HOSSEINI_VPOP_PROFILE_HORIZON_DAYS:-42}" \
SUSILO_EFAST_HOSSEINI_VPOP_SAVEAT_DT="${SUSILO_EFAST_HOSSEINI_VPOP_SAVEAT_DT:-0.125}" \
SUSILO_EFAST_HOSSEINI_VPOP_POST_EVENT_DT="${SUSILO_EFAST_HOSSEINI_VPOP_POST_EVENT_DT:-0.01}" \
SUSILO_EFAST_HOSSEINI_VPOP_BW_KG="${SUSILO_EFAST_HOSSEINI_VPOP_BW_KG:-70}" \
SUSILO_EFAST_HOSSEINI_VPOP_AGGREGATE="${SUSILO_EFAST_HOSSEINI_VPOP_AGGREGATE:-1}" \
nice -n "${NICE_LEVEL}" "${JULIA_BIN}" --project="${JULIA_PROJECT}" "${REPO_DIR}/julia/export_susilo_efast_hosseini2020_fig5_candidates.jl" \
  > "${log_file}" 2>&1

echo "Completed eFAST-derived Hosseini Fig.5 VPop candidate resimulation; log=${log_file}"
