#!/usr/bin/env bash
set -euo pipefail

DEFAULT_PROJECTS_ROOT="${PROJECTS_ROOT:-/projects/${USER:-${LOGNAME:-mosun}}}"
CAMPAIGN_ROOT="${CAMPAIGN_ROOT:-${DEFAULT_PROJECTS_ROOT}/mosun_susilo_fig5_efast}"
JULIA_VERSION="${JULIA_VERSION:-1.12.5}"
JULIA_BIN="${CAMPAIGN_ROOT}/tools/julia-${JULIA_VERSION}/bin/julia"
REPO_DIR="${CAMPAIGN_ROOT}/repo"
JULIA_PROJECT="${REPO_DIR}/julia"
PYTHON_BIN="${PYTHON_BIN:-${CAMPAIGN_ROOT}/pyenvs/vpop-prune/bin/python}"
LOG_ROOT="${LOG_ROOT:-${CAMPAIGN_ROOT}/logs}"
OUT_DIR="${SUSILO_EFAST_HOSSEINI_VPOP_OUT_DIR:-${REPO_DIR}/generated/figures/vpop_pruning/susilo_efast_hosseini2020_fig5_vpop1000_20260516}"
NICE_LEVEL="${NICE_LEVEL:-5}"

mkdir -p "${LOG_ROOT}" "${OUT_DIR}"

export JULIA_DEPOT_PATH="${CAMPAIGN_ROOT}/julia_depot"
export JULIA_NUM_THREADS="${JULIA_NUM_THREADS:-100}"
export OPENBLAS_NUM_THREADS=1
export OMP_NUM_THREADS=1
export JULIA_PKG_PRECOMPILE_AUTO=0

export SUSILO_EFAST_HOSSEINI_VPOP_OUT_DIR="${OUT_DIR}"
export SUSILO_EFAST_VPOP_N_RESIM="${SUSILO_EFAST_VPOP_N_RESIM:-60000}"
export SUSILO_EFAST_VPOP_SEED="${SUSILO_EFAST_VPOP_SEED:-20260516}"
export SUSILO_EFAST_VPOP_PREFILTER_POOL="${SUSILO_EFAST_VPOP_PREFILTER_POOL:-300000}"
export SUSILO_EFAST_VPOP_BEST_ALWAYS="${SUSILO_EFAST_VPOP_BEST_ALWAYS:-12000}"
export SUSILO_EFAST_HOSSEINI_VPOP_SHARD_SIZE="${SUSILO_EFAST_HOSSEINI_VPOP_SHARD_SIZE:-100}"
export SUSILO_EFAST_HOSSEINI_VPOP_RESIM_LIMIT="${SUSILO_EFAST_HOSSEINI_VPOP_RESIM_LIMIT:-0}"
export SUSILO_EFAST_HOSSEINI_VPOP_SOLVER="${SUSILO_EFAST_HOSSEINI_VPOP_SOLVER:-rodas4p}"
export SUSILO_EFAST_HOSSEINI_VPOP_HORIZON_DAYS="${SUSILO_EFAST_HOSSEINI_VPOP_HORIZON_DAYS:-84}"
export SUSILO_EFAST_HOSSEINI_VPOP_PROFILE_HORIZON_DAYS="${SUSILO_EFAST_HOSSEINI_VPOP_PROFILE_HORIZON_DAYS:-42}"
export SUSILO_EFAST_HOSSEINI_VPOP_SAVEAT_DT="${SUSILO_EFAST_HOSSEINI_VPOP_SAVEAT_DT:-0.125}"
export SUSILO_EFAST_HOSSEINI_VPOP_POST_EVENT_DT="${SUSILO_EFAST_HOSSEINI_VPOP_POST_EVENT_DT:-0.01}"
export SUSILO_EFAST_HOSSEINI_VPOP_BW_KG="${SUSILO_EFAST_HOSSEINI_VPOP_BW_KG:-70}"
export SUSILO_EFAST_HOSSEINI_VPOP_AGGREGATE="${SUSILO_EFAST_HOSSEINI_VPOP_AGGREGATE:-1}"
export SUSILO_EFAST_VPOP_SELECT_N="${SUSILO_EFAST_VPOP_SELECT_N:-1000}"
export SUSILO_EFAST_VPOP_OUTPUT_STEM="${SUSILO_EFAST_VPOP_OUTPUT_STEM:-selected_vpop1000}"
export SUSILO_EFAST_VPOP_META_BASENAME="${SUSILO_EFAST_VPOP_META_BASENAME:-vpop1000_meta.json}"
export SUSILO_EFAST_VPOP_PRUNE_SEED="${SUSILO_EFAST_VPOP_PRUNE_SEED:-20260516}"
export SUSILO_EFAST_VPOP_PRUNE_INITIAL_CANDIDATES="${SUSILO_EFAST_VPOP_PRUNE_INITIAL_CANDIDATES:-600}"
export SUSILO_EFAST_VPOP_PRUNE_STARTS="${SUSILO_EFAST_VPOP_PRUNE_STARTS:-24}"
export SUSILO_EFAST_VPOP_PRUNE_SWAP_ITERATIONS="${SUSILO_EFAST_VPOP_PRUNE_SWAP_ITERATIONS:-3000}"
export SUSILO_EFAST_VPOP_RANDOM_BASELINES="${SUSILO_EFAST_VPOP_RANDOM_BASELINES:-100}"
export SUSILO_EFAST_VPOP_PRUNE_WORKERS="${SUSILO_EFAST_VPOP_PRUNE_WORKERS:-24}"
export SUSILO_EFAST_VPOP_USE_SINKHORN="${SUSILO_EFAST_VPOP_USE_SINKHORN:-1}"
export SUSILO_EFAST_VPOP_SINKHORN_TARGET_N="${SUSILO_EFAST_VPOP_SINKHORN_TARGET_N:-501}"
export SUSILO_EFAST_VPOP_SINKHORN_EPSILON="${SUSILO_EFAST_VPOP_SINKHORN_EPSILON:-4.0}"
export SUSILO_EFAST_VPOP_SINKHORN_TAU="${SUSILO_EFAST_VPOP_SINKHORN_TAU:-0.65}"
export SUSILO_EFAST_VPOP_SINKHORN_ITERATIONS="${SUSILO_EFAST_VPOP_SINKHORN_ITERATIONS:-150}"
export SUSILO_EFAST_VPOP_SINKHORN_STRENGTH="${SUSILO_EFAST_VPOP_SINKHORN_STRENGTH:-0.80}"
export SUSILO_EFAST_VPOP_CALIBRATION_WEIGHT="${SUSILO_EFAST_VPOP_CALIBRATION_WEIGHT:-0.95}"
export SUSILO_EFAST_VPOP_DIVERSITY_WEIGHT="${SUSILO_EFAST_VPOP_DIVERSITY_WEIGHT:-0.05}"
export SUSILO_EFAST_VPOP_TUMOR_WATERFALL_WEIGHT="${SUSILO_EFAST_VPOP_TUMOR_WATERFALL_WEIGHT:-0.8}"
export SUSILO_EFAST_VPOP_TUMOR_RESPONDER_WEIGHT="${SUSILO_EFAST_VPOP_TUMOR_RESPONDER_WEIGHT:-0.2}"

log_file="${LOG_ROOT}/susilo_efast_hosseini2020_fig5_vpop1000_$(date +%Y%m%d_%H%M%S).log"
echo "Running Hosseini Fig.5 VPop1000 build: out=${OUT_DIR}, candidates=${SUSILO_EFAST_VPOP_N_RESIM}, threads=${JULIA_NUM_THREADS}, prune_workers=${SUSILO_EFAST_VPOP_PRUNE_WORKERS}, log=${log_file}"

cd "${REPO_DIR}"
{
  if [[ ! -x "${PYTHON_BIN}" ]]; then
    echo "Python environment not found at ${PYTHON_BIN}; cannot run VPop1000 workflow."
    exit 2
  fi
  if ! "${PYTHON_BIN}" -c "import matplotlib, numpy, pandas" >/dev/null 2>&1; then
    echo "${PYTHON_BIN} is missing matplotlib/numpy/pandas; cannot run VPop1000 workflow."
    exit 2
  fi

  echo "[$(date --iso-8601=seconds)] Step 1/3: build expanded candidate parameter set"
  "${PYTHON_BIN}" "${REPO_DIR}/scripts/build_susilo_efast_hosseini2020_vpop250_candidate_set.py"

  echo "[$(date --iso-8601=seconds)] Step 2/3: resimulate expanded candidate trajectories"
  nice -n "${NICE_LEVEL}" "${JULIA_BIN}" --project="${JULIA_PROJECT}" "${REPO_DIR}/julia/export_susilo_efast_hosseini2020_fig5_candidates.jl"

  echo "[$(date --iso-8601=seconds)] Step 3/3: prune to VPop1000"
  "${PYTHON_BIN}" "${REPO_DIR}/scripts/prune_susilo_efast_hosseini2020_fig5_vpop250.py"

  echo "[$(date --iso-8601=seconds)] Postprocess: compare VPop250 and VPop1000 against digitized targets"
  "${PYTHON_BIN}" "${REPO_DIR}/scripts/compare_susilo_efast_hosseini2020_vpop250_vpop1000.py"

  echo "[$(date --iso-8601=seconds)] Completed Hosseini Fig.5 VPop1000 build"
} > "${log_file}" 2>&1

echo "Launched/completed Hosseini Fig.5 VPop1000 workflow; log=${log_file}"
