function export_generatecode_bundle_2025b()
% Export SimBiology generateCode outputs (R2025b+) for translation workflows.
%
% Outputs:
% - generated/model_generatecode_bundle_2025b/models/model_<scenario>.m
% - generated/model_generatecode_bundle_2025b/scenario_manifest.tsv
% - generated/model_generatecode_bundle_2025b/README.txt
%
% Each model_<scenario>.m is generated from SimBiology.Model/generateCode with
% full defaults and configset included, capturing active variant/dose context.

set(0, 'DefaultFigureVisible', 'off');
warning('off', 'all');

repo_root = fileparts(fileparts(mfilename('fullpath')));
matlab_dir = fullfile(repo_root, 'assets', 'Supp Matlab Code');
out_dir = fullfile(repo_root, 'generated', 'model_generatecode_bundle_2025b');
models_dir = fullfile(out_dir, 'models');

if ~exist(out_dir, 'dir'), mkdir(out_dir); end
if ~exist(models_dir, 'dir'), mkdir(models_dir); end

fprintf('Loading model from: %s\n', matlab_dir);
cd(matlab_dir);
addpath(matlab_dir);

s = sbioloadproject('TDBr26_6_paper.sbproj');
c = struct2cell(s);
model = c{1};

scenario_rows = {};
row = 1;

% Snapshot project-default active states to preserve exactly what is in project.
default_variant_active = arrayfun(@(v) logical(v.Active), model.Variants);
default_dose_active = arrayfun(@(d) logical(d.Active), model.Doses);
default_variant_ids = find(default_variant_active);
default_dose_ids = find(default_dose_active);

scenarios = {
    struct( ...
        'name', 'project_default_active', ...
        'variant_ids', default_variant_ids, ...
        'dose_ids', default_dose_ids, ...
        'notes', 'Active flags exactly as loaded from sbproj.'), ...
    struct( ...
        'name', 'all_variants_all_doses_off', ...
        'variant_ids', [], ...
        'dose_ids', [], ...
        'notes', 'Deterministic baseline with all variants and doses inactive.'), ...
    struct( ...
        'name', 'legacy_case10_variantpool_dosepool', ...
        'variant_ids', [5, 9, 11, 13, 14, 24], ...
        'dose_ids', [7, 8, 18, 19], ...
        'notes', 'Legacy paper case 10-13 variant set and dose pool.'), ...
    struct( ...
        'name', 'legacy_case20_variantpool_dosepool', ...
        'variant_ids', [5, 9, 11, 13, 14, 15, 24], ...
        'dose_ids', [7, 8, 18, 19], ...
        'notes', 'Legacy paper case 20-22 variant set and dose pool.'), ...
    struct( ...
        'name', 'legacy_case30_variantpool_dosepool', ...
        'variant_ids', [5, 9, 11, 13, 14, 20, 22, 24], ...
        'dose_ids', [8, 19, 20], ...
        'notes', 'Legacy paper case 30 variant set and dose pool.'), ...
    struct( ...
        'name', 'phase1_human_variantset_no_dose', ...
        'variant_ids', [5, 9, 14, 20, 24, 25, 27, 28], ...
        'dose_ids', [], ...
        'notes', 'Phase-1 human context variant set with no active project dose.'), ...
    struct( ...
        'name', 'phase1_human_variantset_dose27_active', ...
        'variant_ids', [5, 9, 14, 20, 24, 25, 27, 28], ...
        'dose_ids', [27], ...
        'notes', 'Phase-1 human variants with project dose 27 (TDB 0.8 mg 8q3w) active.')
};

for i = 1:numel(scenarios)
    sc = scenarios{i};
    apply_active_flags(model, sc.variant_ids, sc.dose_ids);

    safe_name = sanitize_filename(sc.name);
    out_m = fullfile(models_dir, ['model_' safe_name '.m']);
    gc = generateCode( ...
        model, ...
        out_m, ...
        'IncludeConfigset', true, ...
        'IncludeDefaultValues', true, ...
        'IncludeComments', true, ...
        'IncludeRelease', true, ...
        'OverwriteFile', true, ...
        'OpenEditor', false);

    variant_names = arrayfun(@(v) as_char(v.Name), model.Variants(sc.variant_ids), 'UniformOutput', false);
    dose_names = arrayfun(@(d) as_char(d.Name), model.Doses(sc.dose_ids), 'UniformOutput', false);

    scenario_rows(row, :) = { ...
        sc.name, ...
        jsonencode(sc.variant_ids), ...
        jsonencode(variant_names), ...
        jsonencode(sc.dose_ids), ...
        jsonencode(dose_names), ...
        length(sc.variant_ids), ...
        length(sc.dose_ids), ...
        strlength(string(gc)), ...
        out_m, ...
        sc.notes}; %#ok<AGROW>
    row = row + 1;

    fprintf('Wrote %s\n', out_m);
end

% Restore original project default active flags.
for i = 1:length(model.Variants)
    model.Variants(i).Active = default_variant_active(i);
end
for i = 1:length(model.Doses)
    model.Doses(i).Active = default_dose_active(i);
end

manifest_tbl = cell2table(scenario_rows, 'VariableNames', { ...
    'scenario_name', ...
    'variant_ids_json', ...
    'variant_names_json', ...
    'dose_ids_json', ...
    'dose_names_json', ...
    'n_active_variants', ...
    'n_active_doses', ...
    'code_char_count', ...
    'model_m_file', ...
    'notes'});
manifest_path = fullfile(out_dir, 'scenario_manifest.tsv');
writetable(manifest_tbl, manifest_path, 'FileType', 'text', 'Delimiter', '\t');
fprintf('Wrote %s\n', manifest_path);

readme_path = fullfile(out_dir, 'README.txt');
write_text(readme_path, readme_text());
fprintf('Wrote %s\n', readme_path);

fprintf('\nDone. generateCode bundle written to:\n%s\n', out_dir);
end


function apply_active_flags(model, variant_ids, dose_ids)
for i = 1:length(model.Variants)
    model.Variants(i).Active = false;
end
for i = 1:length(model.Doses)
    model.Doses(i).Active = false;
end

for i = 1:numel(variant_ids)
    model.Variants(variant_ids(i)).Active = true;
end
for i = 1:numel(dose_ids)
    model.Doses(dose_ids(i)).Active = true;
end
end


function s = sanitize_filename(name)
s = as_char(name);
s = regexprep(s, '[^A-Za-z0-9_]+', '_');
s = regexprep(s, '_+', '_');
s = regexprep(s, '^_+', '');
s = regexprep(s, '_+$', '');
if isempty(s)
    s = 'unnamed';
end
end


function out = as_char(x)
if isstring(x)
    out = char(x);
elseif ischar(x)
    out = x;
elseif isempty(x)
    out = '';
else
    out = char(string(x));
end
end


function write_text(path, txt)
f = fopen(path, 'w');
if f < 0
    error('Could not open for writing: %s', path);
end
fprintf(f, '%s', txt);
fclose(f);
end


function txt = readme_text()
txt = [ ...
    "This folder contains MATLAB code generated from the SimBiology project", newline, ...
    "using SimBiology.Model/generateCode in MATLAB R2025b.", newline, ...
    newline, ...
    "Files:", newline, ...
    "- models/model_<scenario>.m : full model reconstruction code (components + defaults + configset)", newline, ...
    "- scenario_manifest.tsv : active variant/dose context used for each generated model file", newline, ...
    newline, ...
    "Notes:", newline, ...
    "- generateCode captures all model components (species/reactions/rules/variants/doses).", newline, ...
    "- Active flags in each generated model file match the scenario context at export time.", newline, ...
    "- This code is intended as a lossless intermediate for Julia translation.", newline];
end
